### ISSUE TITLE
Fatal error: Uncaught TypeError: count() … must be of type Countable|array, bool given with PHP 8.2 / txp 4.9

### ISSUE THREAD

**Issue by jools-r** [Bloke/smd_query#3]
Again with PHP 8.2 with txp 4.9-dev, I get the following fatal error:

`Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, bool given … {long message} … on line 171.`

which is referring to this line: https://github.com/Bloke/smd_query/blob/34404c58dfbac47628bc84ee18b3df76018b6233/smd_query.php#L242

The error seems to occur when there's no match. Changing this to:

`$numrows = (!$rs ? 0 : count($rs));`

seems to have resolved it.

(BTW: I'm not sure if this is related to dragondz's other Issue https://github.com/Bloke/smd_query/issues/1)

**Comment by jools-r** [comment]
Came up against this before when there were no relevant entries. My earlier suggestion helped.

**Comment by Bloke** [comment]
Oops, forgot about this, sorry. I'll try and commit your patch asap.
